//
//  Icons.h
//  Simple Subway
//
//  Created by Bolt Action on 8/14/17.
//  Copyright © 2017 SMG Mobile. All rights reserved.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

@import UIKit;



@interface Icons : NSObject


#pragma mark - Resizing Behavior

typedef enum : NSInteger {
    IconsResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    IconsResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    IconsResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    IconsResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.
} IconsResizingBehavior;

extern CGRect IconsResizingBehaviorApply(IconsResizingBehavior behavior, CGRect rect, CGRect target);


#pragma mark - Canvas Drawings

//! Page 1
+ (void)drawInfoFilled;
+ (void)drawInfoFilledWithFrame:(CGRect)targetFrame resizing:(IconsResizingBehavior)resizing;
+ (void)drawMapFilled;
+ (void)drawMapFilledWithFrame:(CGRect)targetFrame resizing:(IconsResizingBehavior)resizing;
+ (void)drawSubFilled;
+ (void)drawSubFilledWithFrame:(CGRect)targetFrame resizing:(IconsResizingBehavior)resizing;
+ (void)drawBusFilled;
+ (void)drawBusFilledWithFrame:(CGRect)targetFrame resizing:(IconsResizingBehavior)resizing;
+ (void)drawBicycleFilled;
+ (void)drawBicycleFilledWithFrame:(CGRect)targetFrame resizing:(IconsResizingBehavior)resizing;


#pragma mark - Canvas Images

//! Page 1
+ (UIImage *)imageOfInfoFilled;
+ (UIImage *)imageOfMapFilled;
+ (UIImage *)imageOfSubFilled;
+ (UIImage *)imageOfBusFilled;
+ (UIImage *)imageOfBicycleFilled;


@end
